# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go-bhaskar(00e50ed8-8092-412e-b717-6f7dd43d9b31)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'ls -ltr'
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
